package com.wb.paliver;

public class MarchMadness2017 {

	public static String[] Subjects = { 
		"Villanova",
		"Mount St Marys",
		"Wisconsin",
		"Virginia Tech",
		"Virginia",
		"UNC Wilmington",
		"Florida",
		"East Tenn St",
		"SMU",
		"Providence", "USC",
		"Baylor",
		"New Mexico St",
		"South Carolina",
		"Marquette",
		"Duke",
		"Troy",

		"Gonzaga",
		"S Dakota St",
		"Northwestern",
		"Vanderbilt",
		"Notre Dame",
		"Princeton",
		"West Virginia",
		"Bucknell",
		"Maryland",
		"Xavier",
		"Florida St",
		"Fla Gulf Coast",
		"Saint Marys",
		"VCU",
		"Arizona",
		"North Dakota",

		"Kansas",
		"NC Central", "UC Davis",
		"Miami",
		"Michigan St",
		"Iowa St",
		"Nevada",
		"Purdue",
		"Vermont",
		"Creighton",
		"Rhode Island",
		"Oregon",
		"Iona",
		"Michigan",
		"Oklahoma St",
		"Louisville",
		"Jacksonville St",

		"North Carolina",
		"Texas Southern",
		"Arkansas",
		"Seton Hall",
		"Minnesota",
		"Middle Tenn",
		"Butler",
		"Winthrop",
		"Cincinnati",
		"Kansas St",
		"UCLA",
		"Kent St",
		"Dayton",
		"Wichita St",
		"Kentucky",
		"Northern Ky"
	};
}
